"""initial_schema

Revision ID: e2a929559a5b
Revises: add1f9ba9d34
Create Date: 2026-02-24 14:25:27.520236+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2a929559a5b"
down_revision: Union[str, Sequence[str], None] = "add1f9ba9d34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_number", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cases_case_number"), "cases", ["case_number"], unique=True
    )
    op.create_index(op.f("ix_cases_id"), "cases", ["id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("artifact_type", sa.String(length=50), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_hash_md5", sa.String(length=32), nullable=True),
        sa.Column("file_hash_sha256", sa.String(length=64), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifacts_case_id"), "artifacts", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_artifacts_file_hash_md5"),
        "artifacts",
        ["file_hash_md5"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifacts_file_hash_sha256"),
        "artifacts",
        ["file_hash_sha256"],
        unique=False,
    )
    op.create_index(op.f("ix_artifacts_id"), "artifacts", ["id"], unique=False)
    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artifact_id", sa.Integer(), nullable=False),
        sa.Column("module_name", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("result_path", sa.String(length=500), nullable=True),
        sa.Column("result_summary", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analyses_artifact_id"),
        "analyses",
        ["artifact_id"],
        unique=False,
    )
    op.create_index(op.f("ix_analyses_id"), "analyses", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analyses_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_artifact_id"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_artifacts_id"), table_name="artifacts")
    op.drop_index(
        op.f("ix_artifacts_file_hash_sha256"), table_name="artifacts"
    )
    op.drop_index(op.f("ix_artifacts_file_hash_md5"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_case_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_cases_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_case_number"), table_name="cases")
    op.drop_table("cases")
    # ### end Alembic commands ###
